1. Импортируйте пакет numpy под именем np

In [6]:
import numpy as np

2. Распечатайте версию numpy

In [7]:
print(np.__version__)

2.1.3


3. Создайте вектор со значениями от 10 до 49 

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [11]:
array = np.arange(10, 50)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Перевернуть вектор (первый элемент становится последним)

In [18]:
reversed_array = np.flip(array)
print(reversed_array)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


5. Создайте массив 5x5 со случайными значениями и найдите среднее значение и медиану для каждой строки

In [19]:
A = np.random.random((5,5))
print(A)

[[0.11048527 0.1089386  0.20376642 0.37934443 0.91776057]
 [0.55071345 0.25858587 0.64436023 0.11144468 0.7723636 ]
 [0.9512133  0.17411845 0.54444    0.01153456 0.74218849]
 [0.95335755 0.9921539  0.49835523 0.07473686 0.6618443 ]
 [0.99120206 0.4293114  0.54354227 0.45479052 0.77417438]]


In [20]:
mean_values = np.mean(A, axis=1)
print("\nСредние значения по строкам:")
print(mean_values)
median_values = np.median(A, axis=1)
print("\nМедианы по строкам:")
print(median_values)


Средние значения по строкам:
[0.34405906 0.46749357 0.48469896 0.63608957 0.63860413]

Медианы по строкам:
[0.20376642 0.55071345 0.54444    0.6618443  0.54354227]


6. Преобразуйте одномерный массив из 27 элементов целого типа в трехмерный (3x3x3)

In [22]:
a = np.array([x for x in range(27)])

In [23]:
b = a.reshape(3, 3, 3)
print(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


7. Преобразуйте все элементы массива numpy из типа данных float в integer

In [29]:
a = np.array([[3.5, 1.9, 8.45], [4.7, 7.9, 1.9]])

In [30]:
b = a.astype(int)
print(b)

[[3 1 8]
 [4 7 1]]


8. Преобразуйте двоичный массив numpy [[1, 0, 0], [1, 1, 1],  [0, 0, 1]] (содержащий только 0 и 1) в логический массив numpy

In [26]:
a = np.array([[1, 0, 0], [1, 1, 1],  [0, 0, 1]])

In [28]:
b = a.astype(bool)
print(b)

[[ True False False]
 [ True  True  True]
 [False False  True]]


9. Расположите 2 массива numpy горизонтально (hstack), т.е. 2 массива, имеющих одинаковое 1-е измерение (количество строк в 2D-массивах)

In [31]:
a1 = np.array([[1,2,3], [4,5,6]])
a2 = np.array([[7,8,9], [10,11,12]])

In [32]:
np.hstack((a1, a2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

10. Расположите 2 массива numpy вертикально (vstack), т.е. 2 массива, имеющие одинаковое последнее измерение (количество столбцов в 2D-массивах)

In [42]:
a1 = np.array([[1,2],
 [3,4],
 [5,6]])

a2 = np.array([[7,8],
 [9,10],
 [10,11]])

In [33]:
np.vstack((a1, a2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

11. Из 2 массивов numpy извлеките индексы, в которых совпадают элементы (np.where)

In [39]:
a = np.array([1,2,3,4,5])
b = np.array([1,3,2,4,5])

In [40]:
np.where(a == b)

(array([0, 3, 4]),)

12. Выведите результат умножения 2 матриц (в виде массива numpy)

In [45]:
a = np.array([[1,2,3], 
 [4,5,6], 
 [7,8,9]])

b = np.array([[2,3,4], 
 [5,6,7], 
 [8,9,10]])

In [49]:
np.dot(a,b)


array([[ 36,  42,  48],
       [ 81,  96, 111],
       [126, 150, 174]])

In [48]:
a @ b

array([[ 36,  42,  48],
       [ 81,  96, 111],
       [126, 150, 174]])

13. Выведите транспонированную матрицу

In [50]:
a = np.array([[1,2,3], 
 [4,5,6], 
 [7,8,9]])

In [51]:
print(np.transpose(a))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [52]:
np.transpose(a)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

14. Вычислите синус массива углов (в радианах) с помощью NumPy

In [53]:
angles = np.array([3.14, 3.14/2, 6.28])

In [54]:
np.sin(angles)

array([ 0.00159265,  0.99999968, -0.0031853 ])

15. Отсортировать вектор

In [55]:
v = np.random.random(size=[10])
print(v)

[0.31702258 0.5346938  0.34534242 0.52650099 0.74629327 0.09925136
 0.46196892 0.2577297  0.45328852 0.99809703]


In [56]:
np.sort(v)

array([0.09925136, 0.2577297 , 0.31702258, 0.34534242, 0.45328852,
       0.46196892, 0.52650099, 0.5346938 , 0.74629327, 0.99809703])

16. Проверить, одинаковы ли два NumPy массива

In [66]:
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])

In [68]:
np.array_equal(a, b)

True

17. В одномерном массиве заменить максимальный элемент на ноль

In [74]:
Z = np.random.random(10)

In [75]:
max_index = np.argmax(Z)
print("\nДо замены")
print(Z)
Z[max_index] = 0
print("\nПосле")
print(Z)


До замены
[0.68861353 0.23893147 0.58036573 0.50985033 0.50287103 0.45344706
 0.23377434 0.50143343 0.82046663 0.59034547]

После
[0.68861353 0.23893147 0.58036573 0.50985033 0.50287103 0.45344706
 0.23377434 0.50143343 0.         0.59034547]


18. Замените все нечетные числа одномерного массива на -1.

In [76]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
asd = arr % 2 == 1
arr[asd] = -1

In [78]:
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. Замените все элементы в массиве NumPy больше 30 или меньше 5 новым значением 10 

In [83]:
arr = np.array([0, 1, 20, 3, 4, 5, 6, -7, 8, 90])

In [84]:
asd = (arr < 5) | (arr > 30)
arr[asd] = 10

In [85]:
arr

array([10, 10, 20, 10, 10,  5,  6, 10,  8, 10])

20. Отсортируйте двумерный массив по столбцам

In [87]:
a = np.array([[11,5,3], 
 [4,15,6], 
 [7,8,19]])

In [88]:
np.sort(a, axis=0)

array([[ 4,  5,  3],
       [ 7,  8,  6],
       [11, 15, 19]])